# Generated by Django 4.2.9 on 2024-01-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EU', 'EU')], max_length=3, verbose_name='Para Birimi')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('shor_name', models.CharField(max_length=100, verbose_name='Adı')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('document_no', models.CharField(max_length=155, verbose_name='Rehber No')),
                ('phone', models.CharField(max_length=155, verbose_name='Telefon No')),
                ('mail', models.CharField(max_length=155, verbose_name='Mail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EU', 'EU')], max_length=3, verbose_name='Para Birimi')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('mail', models.CharField(max_length=155, verbose_name='Mail')),
                ('one_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tek Kişilik Ücreti')),
                ('two_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İki Kişilik Ücreti')),
                ('tree_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Üç Kişilik Ücreti')),
                ('finish', models.DateField(verbose_name='Fiyat Geçerlilik Tarihi')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EU', 'EU')], max_length=3, verbose_name='Para Birimi')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EU', 'EU')], max_length=3, verbose_name='Para Birimi')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Başlama Tarihi')),
                ('finish', models.DateField(verbose_name='Bitiş Tarihi')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('passenger_info', models.TextField(verbose_name='Yolcu Bilgileri')),
                ('ticket', models.CharField(max_length=50, unique=True, verbose_name='Etiket')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Satış Fiyatı')),
                ('buyer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alıcı', to='TourManager.buyercompany', verbose_name='Alıcı Firma')),
            ],
        ),
        migrations.CreateModel(
            name='OperationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Adı')),
                ('start', models.DateField(verbose_name='Başlama Tarihi')),
                ('finish', models.DateField(verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(verbose_name='Aktif mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=155, verbose_name='Araçlar')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasite')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=155, verbose_name='Güzergah')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=155, verbose_name='Güzergah')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='Aktif mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Karsilama', 'Karşılama'), ('Ugurlama', 'Uğurlama'), ('Tur', 'Tur'), ('Transfer', 'Transfer'), ('Arac', 'Araç'), ('Aktivite', 'Aktivite'), ('Muze', 'Müze'), ('Otel', 'Otel'), ('Rehber', 'Rehber'), ('Aracli Rehber', 'Araçlı Rehber'), ('Serbest Zaman', 'Serbest Zaman')], max_length=20, verbose_name='işlem Türü')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('room_type', models.CharField(choices=[('Tek', 'Tek'), ('Cift', 'Çift'), ('Uc', 'Üç')], max_length=20, verbose_name='Oda Türü')),
                ('hotel_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otel Ücreti')),
                ('guide_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rehber Ücreti')),
                ('activity_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aktivite Ücreti')),
                ('museym_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Müze Ücreti')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.activity', verbose_name='Aktivite')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.operationday', verbose_name='Gün')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.guide', verbose_name='Rehber')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.hotel', verbose_name='Otel')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.museum', verbose_name='Müze')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.tour', verbose_name='Tur')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.transfer', verbose_name='Transfer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.vehicle', verbose_name='Araç')),
            ],
        ),
        migrations.AddField(
            model_name='operationday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket'),
        ),
        migrations.AddField(
            model_name='operationday',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.operation', verbose_name='Operasyon'),
        ),
        migrations.AddField(
            model_name='operation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket'),
        ),
        migrations.AddField(
            model_name='operation',
            name='follow_staf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Takip', to='TourManager.personel', verbose_name='Takip Eden Personel'),
        ),
        migrations.AddField(
            model_name='operation',
            name='selling_staf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Satan', to='TourManager.personel', verbose_name='Satan Personel'),
        ),
        migrations.AddField(
            model_name='museum',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket'),
        ),
        migrations.AddField(
            model_name='guide',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket'),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Binek')),
                ('minivan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minivan')),
                ('minibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minibüs')),
                ('midibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Midibüs')),
                ('bus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Otobüs')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EU', 'EU')], max_length=3, verbose_name='Para Birimi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.supplier', verbose_name='Tedarikçi')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TourManager.tour', verbose_name='Tur')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TourManager.transfer', verbose_name='Transfer')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket'),
        ),
    ]
