# Generated by Django 4.2.9 on 2024-01-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='currency',
        ),
    ]
