# Generated by Django 4.2.9 on 2024-01-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0002_remove_activity_contact_remove_activity_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücreti'),
        ),
    ]
