# Generated by Django 4.2.9 on 2024-01-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0004_alter_personel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EU', 'EU')], max_length=3, verbose_name='Para Birimi')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TourManager.activity', verbose_name='Activite')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourManager.activitysupplier', verbose_name='Aktivite Tedarikçisi')),
            ],
        ),
    ]
