# Generated by Django 4.2.9 on 2024-01-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0007_remove_supplier_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysupplier',
            name='city',
        ),
    ]
