# Generated by Django 4.2.9 on 2024-01-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0008_remove_activitysupplier_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TourManager.sirket', verbose_name='Sirket'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='operation_type',
            field=models.CharField(choices=[('Karsilama', 'Karşılama'), ('Ugurlama', 'Uğurlama'), ('Tur', 'Tur'), ('Arac', 'Araç'), ('Aktivite', 'Aktivite'), ('Muze', 'Müze'), ('Otel', 'Otel'), ('Rehber', 'Rehber'), ('Aracli Rehber', 'Araçlı Rehber'), ('Serbest Zaman', 'Serbest Zaman')], max_length=20, verbose_name='işlem Türü'),
        ),
    ]
