# Generated by Django 4.2.9 on 2024-01-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0009_buyercompany_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyercompany',
            old_name='shor_name',
            new_name='short_name',
        ),
    ]
