# Generated by Django 4.2.9 on 2024-01-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0010_rename_shor_name_buyercompany_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyercompany',
            name='short_name',
            field=models.CharField(max_length=5, verbose_name='Kısa adı'),
        ),
    ]
