# Generated by Django 4.2.9 on 2024-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0012_rename_follow_staf_operation_follow_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EU', 'EU')], default='USD', max_length=3, verbose_name='Para Birimi'),
        ),
    ]
