# Generated by Django 4.2.9 on 2024-01-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0013_operation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='selling_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Satan', to='TourManager.personel', verbose_name='Satan Personel'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='ticket',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Etiket'),
        ),
    ]
