# Generated by Django 4.2.9 on 2024-01-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0015_alter_operationitem_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='number_passengers',
            field=models.PositiveIntegerField(default=0, verbose_name='Etiket'),
        ),
    ]
