# Generated by Django 4.2.9 on 2024-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourManager', '0016_operation_number_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='number_passengers',
            field=models.PositiveIntegerField(default=1, verbose_name='Yolcu Sayısı'),
        ),
    ]
