# Generated by Django 4.2.9 on 2024-01-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0017_alter_operation_number_passengers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycost",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="document_no",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Rehber No"
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="mail",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Mail"
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="museum",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="buyer_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Alıcı",
                to="TourManager.buyercompany",
                verbose_name="Alıcı Firma (买方公司)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.sirket",
                verbose_name="Şirket (公司)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi (创建日期)"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL (土耳其里拉)"),
                    ("USD", "USD (美元)"),
                    ("EUR", "EUR (欧元)"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Para Birimi (货币)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="finish",
            field=models.DateField(verbose_name="Bitiş Tarihi (结束日期)"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="follow_staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Takip",
                to="TourManager.personel",
                verbose_name="Takip Eden Personel (跟进员工)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="number_passengers",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Yolcu Sayısı (乘客数量)"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="passenger_info",
            field=models.TextField(verbose_name="Yolcu Bilgileri (乘客信息)"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="sales_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Satış Fiyatı (销售价格)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="selling_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Satan",
                to="TourManager.personel",
                verbose_name="Satan Personel (销售人员)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="start",
            field=models.DateField(verbose_name="Başlama Tarihi (开始日期)"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="ticket",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Etiket (标签)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncelleme Tarihi (更新日期)"
            ),
        ),
        migrations.AlterField(
            model_name="operationday",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.sirket",
                verbose_name="Şirket (公司)",
            ),
        ),
        migrations.AlterField(
            model_name="operationday",
            name="date",
            field=models.DateField(verbose_name="Tarih (日期)"),
        ),
        migrations.AlterField(
            model_name="operationday",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.operation",
                verbose_name="Operasyon (操作)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.activity",
                verbose_name="Aktivite (活动)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="activity_cost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.activitycost",
                verbose_name="Aktivite Tedarikçi (活动供应商)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Aktivite Ücreti (活动费)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.sirket",
                verbose_name="Şirket (公司)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="cost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.cost",
                verbose_name="Araç Tedarikçi (车辆供应商)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.operationday",
                verbose_name="Gün (日)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Açıklama (描述)"
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="guide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.guide",
                verbose_name="Rehber (导游)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="guide_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Rehber Ücreti (导游费)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.hotel",
                verbose_name="Otel (酒店)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="hotel_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Otel Ücreti (酒店价格)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.museum",
                verbose_name="Müze (博物馆)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museym_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Müze Ücreti (博物馆费用)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("Karsilama", "Karşılama (迎接)"),
                    ("Ugurlama", "Uğurlama (送别)"),
                    ("Tur", "Tur (旅游)"),
                    ("Arac", "Araç (车辆)"),
                    ("Aktivite", "Aktivite (活动)"),
                    ("Muze", "Müze (博物馆)"),
                    ("Otel", "Otel (酒店)"),
                    ("Rehber", "Rehber (导游)"),
                    ("Aracli Rehber", "Araçlı Rehber (带车导游)"),
                    ("Serbest Zaman", "Serbest Zaman (自由时间)"),
                ],
                max_length=20,
                verbose_name="İşlem Türü (操作类型)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="room_type",
            field=models.CharField(
                blank=True,
                choices=[("Tek", "Tek (单人)"), ("Cift", "Çift (双人)"), ("Uc", "Üç (三人)")],
                max_length=20,
                null=True,
                verbose_name="Oda Türü (房间类型)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.tour",
                verbose_name="Tur (旅游)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.transfer",
                verbose_name="Transfer (转移)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.vehicle",
                verbose_name="Araç (车辆)",
            ),
        ),
    ]
