# Generated by Django 4.2.9 on 2024-01-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TourManager",
            "0018_alter_activitycost_currency_alter_cost_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
    ]
