# Generated by Django 4.2.9 on 2024-01-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0019_alter_guide_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="document_no",
            field=models.CharField(max_length=155, verbose_name="Rehber No"),
        ),
        migrations.AlterField(
            model_name="guide",
            name="mail",
            field=models.CharField(max_length=155, verbose_name="Mail"),
        ),
        migrations.AlterField(
            model_name="guide",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ücreti"
            ),
        ),
    ]
