# Generated by Django 4.2.9 on 2024-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0020_alter_guide_document_no_alter_guide_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="document_no",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Rehber No"
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="mail",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Mail"
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ücreti"
            ),
        ),
    ]
