# Generated by Django 4.2.9 on 2024-01-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0021_alter_guide_document_no_alter_guide_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="car",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Binek",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
    ]
