# Generated by Django 4.2.9 on 2024-01-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0023_alter_buyercompany_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyercompany",
            name="short_name",
            field=models.CharField(max_length=5, unique=True, verbose_name="Kısa adı"),
        ),
    ]
