# Generated by Django 4.2.9 on 2024-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0024_alter_buyercompany_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="finish",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fiyat Geçerlilik Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="mail",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Mail"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="one_person",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Tek Kişilik Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="tree_person",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Üç Kişilik Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="two_person",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="İki Kişilik Ücreti",
            ),
        ),
    ]
