# Generated by Django 4.2.9 on 2024-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0025_alter_hotel_currency_alter_hotel_finish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="driver",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Şoför (司机)"
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="pick_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Alış Saati (接载时间)"
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="plaka",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Plaka (牌照号码是)"
            ),
        ),
    ]
