# Generated by Django 4.2.9 on 2024-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0031_alter_operationitem_activity_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycost",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="museum",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL (土耳其里拉)"),
                    ("USD", "USD (美元)"),
                    ("EUR", "EUR (欧元)"),
                    ("RMB", "RMB (人民币)"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Para Birimi (货币)",
            ),
        ),
    ]
