# Generated by Django 4.2.9 on 2024-01-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0034_alter_operationitem_pick_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="sales_price",
        ),
        migrations.AddField(
            model_name="operation",
            name="eur_sales_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="EUR Satış Fiyatı (销售价格)",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="rbm_sales_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="RBM Satış Fiyatı (人民币 销售价格)",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="tl_sales_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="TL Satış Fiyatı (销售价格)",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="usd_sales_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="USD Satış Fiyatı (销售价格)",
            ),
        ),
    ]
