# Generated by Django 4.2.9 on 2024-01-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0035_remove_operation_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiyatlandirma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(verbose_name="Başlama Tarihi (开始日期)")),
                ("finish", models.DateField(verbose_name="Bitiş Tarihi (结束日期)")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi (创建日期)"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi (更新日期)"
                    ),
                ),
                (
                    "total_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_tour", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_transfer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_hotel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_guide",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_food", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_extra",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_sell", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TourManager.sirket",
                        verbose_name="Şirket (公司)",
                    ),
                ),
                (
                    "create_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TourManager.personel",
                        verbose_name="Oluşturan Personel (销售人员)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FiyatlandirmaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_total_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "item_total_tour",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tur Ücreti",
                    ),
                ),
                (
                    "item_total_transfer",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Transfer Ücreti",
                    ),
                ),
                (
                    "item_total_hotel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Otel Ücreti",
                    ),
                ),
                (
                    "item_total_guide",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Rehber Ücreti",
                    ),
                ),
                (
                    "guide_currency",
                    models.CharField(
                        choices=[
                            ("TL", "TL (土耳其里拉)"),
                            ("USD", "USD (美元)"),
                            ("EUR", "EUR (欧元)"),
                            ("RMB", "RMB (人民币)"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Rehber Para Birimi (货币)",
                    ),
                ),
                (
                    "hotel_currency",
                    models.CharField(
                        choices=[
                            ("TL", "TL (土耳其里拉)"),
                            ("USD", "USD (美元)"),
                            ("EUR", "EUR (欧元)"),
                            ("RMB", "RMB (人民币)"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Otel Para Birimi (货币)",
                    ),
                ),
                (
                    "tour_currency",
                    models.CharField(
                        choices=[
                            ("TL", "TL (土耳其里拉)"),
                            ("USD", "USD (美元)"),
                            ("EUR", "EUR (欧元)"),
                            ("RMB", "RMB (人民币)"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Tur Para Birimi (货币)",
                    ),
                ),
                (
                    "transfer_currency",
                    models.CharField(
                        choices=[
                            ("TL", "TL (土耳其里拉)"),
                            ("USD", "USD (美元)"),
                            ("EUR", "EUR (欧元)"),
                            ("RMB", "RMB (人民币)"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Transfer Para Birimi (货币)",
                    ),
                ),
                (
                    "food_currency",
                    models.CharField(
                        choices=[
                            ("TL", "TL (土耳其里拉)"),
                            ("USD", "USD (美元)"),
                            ("EUR", "EUR (欧元)"),
                            ("RMB", "RMB (人民币)"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Yemek Para Birimi (货币)",
                    ),
                ),
                (
                    "extra_currency",
                    models.CharField(
                        choices=[
                            ("TL", "TL (土耳其里拉)"),
                            ("USD", "USD (美元)"),
                            ("EUR", "EUR (欧元)"),
                            ("RMB", "RMB (人民币)"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Diğer Para Birimi (货币)",
                    ),
                ),
                (
                    "item_total_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Diğer Ücreti",
                    ),
                ),
                (
                    "item_total_food",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Yemek Ücreti",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TourManager.sirket",
                        verbose_name="Şirket (公司)",
                    ),
                ),
                (
                    "fiyatlandirma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TourManager.fiyatlandirma",
                        verbose_name="Fiyatlandırma",
                    ),
                ),
            ],
        ),
    ]
