# Generated by Django 4.2.9 on 2024-01-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0036_fiyatlandirma_fiyatlandirmaitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiyatlandirmaitem",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Tarih (日期)"),
        ),
    ]
