# Generated by Django 4.2.9 on 2024-01-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0038_alter_fiyatlandirma_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Fiyatlandirma",
            new_name="Fiyatlandırma",
        ),
    ]
