# Generated by Django 4.2.9 on 2024-01-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0040_fiyatlandirma_alter_fiyatlandirmaitem_fiyat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiyatlandırma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genel_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Genel Toplam Fiyatı",
                    ),
                ),
                (
                    "arac_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Araç Fiyatı",
                    ),
                ),
                (
                    "transfer_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Transfer Toplam Fiyatı",
                    ),
                ),
                (
                    "rehber_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Rehber Toplam Fiyatı",
                    ),
                ),
                (
                    "yemek_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Yemek Toplam Fiyatı",
                    ),
                ),
                (
                    "double_oda_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Double Oda Toplam Fiyatı",
                    ),
                ),
                (
                    "single_oda_toplam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Single Oda Toplam Fiyatı",
                    ),
                ),
                ("onay", models.BooleanField(default=False, verbose_name="Onay")),
                ("islem", models.BooleanField(default=False, verbose_name="İslem")),
                (
                    "aciklama",
                    models.TextField(default="Beklemede", verbose_name="Açıklama"),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TourManager.personel",
                        verbose_name="Personel",
                    ),
                ),
                (
                    "sirket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TourManager.sirket",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiyatlandırma",
                "verbose_name_plural": "Fiyatlandırmalar",
            },
        ),
        migrations.AlterField(
            model_name="fiyatlandirmaitem",
            name="fiyat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.fiyatlandırma",
                verbose_name="Fiyatlandırma",
            ),
        ),
        migrations.DeleteModel(
            name="Fiyatlandirma",
        ),
    ]
