# Generated by Django 4.2.9 on 2024-01-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0041_fiyatlandırma_alter_fiyatlandirmaitem_fiyat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.supplier",
                verbose_name="Araç Tedarikçi (车辆供应商)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="cost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.cost",
                verbose_name="Araç Maaliyet (车辆供应商)",
            ),
        ),
    ]
