# Generated by Django 4.2.9 on 2024-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0042_operationitem_supplier_alter_operationitem_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationitem",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("Karsilama", "Karşılama (迎接)"),
                    ("Ugurlama", "Uğurlama (送别)"),
                    ("Tur", "Tur (旅游)"),
                    ("TurTransfer", "Tur + Transfer"),
                    ("TransferTur", "Transfer + Tur"),
                    ("Arac", "Araç (车辆)"),
                    ("Aktivite", "Aktivite (活动)"),
                    ("Muze", "Müze (博物馆)"),
                    ("Otel", "Otel (酒店)"),
                    ("Rehber", "Rehber (导游)"),
                    ("Aracli Rehber", "Araçlı Rehber (带车导游)"),
                    ("Serbest Zaman", "Serbest Zaman (自由时间)"),
                ],
                max_length=20,
                verbose_name="İşlem Türü (操作类型)",
            ),
        ),
    ]
