# Generated by Django 4.2.9 on 2024-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0043_alter_operationitem_operation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="vehicle_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Araç Ücreti"
            ),
        ),
    ]
