# Generated by Django 4.2.9 on 2024-01-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0046_useractivitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivitylog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TourManager.sirket",
                verbose_name="Şirket (公司)",
            ),
        ),
    ]
