# Generated by Django 4.2.9 on 2024-02-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0047_useractivitylog_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="sell_bus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Otobüs Satış Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="cost",
            name="sell_car",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Binek Satış Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="cost",
            name="sell_midibus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Midibüs Satış Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="cost",
            name="sell_minibus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Minibüs Satış Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="cost",
            name="sell_minivan",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Minivan Satış Fiyatı",
            ),
        ),
    ]
