# Generated by Django 4.2.9 on 2024-03-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0052_paymentdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPaymentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="payment_documents/%Y/%m/%d/", verbose_name="Dekont"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yükleme Tarihi"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_documents",
                        to="TourManager.supplier",
                        verbose_name="Tedarikci",
                    ),
                ),
            ],
        ),
    ]
