# Generated by Django 4.2.9 on 2024-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0053_supplierpaymentdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpaymentdocument",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ödeme Miktarı",
            ),
        ),
    ]
