# Generated by Django 4.2.9 on 2024-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0054_supplierpaymentdocument_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierpaymentdocument",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="payment_documents/%Y/%m/%d/",
                verbose_name="Dekont",
            ),
        ),
    ]
