# Generated by Django 4.2.9 on 2024-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0055_alter_supplierpaymentdocument_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierpaymentdocument",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ödeme Miktarı"
            ),
        ),
    ]
