# Generated by Django 4.2.9 on 2024-03-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0056_alter_supplierpaymentdocument_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitySupplierPaymentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payment_documents/%Y/%m/%d/",
                        verbose_name="Dekont",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ödeme Miktarı",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yükleme Tarihi"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_documents",
                        to="TourManager.activitysupplier",
                        verbose_name="Tedarikci",
                    ),
                ),
            ],
        ),
    ]
