# Generated by Django 4.2.9 on 2024-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0057_activitysupplierpaymentdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdocument",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ödeme Miktarı"
            ),
        ),
    ]
