# Generated by Django 4.2.9 on 2024-03-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0058_paymentdocument_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitysupplierpaymentdocument",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AddField(
            model_name="paymentdocument",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AddField(
            model_name="supplierpaymentdocument",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "TL"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("RMB", "RMB (人民币)"),
                ],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
    ]
