# Generated by Django 4.2.9 on 2024-03-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0059_activitysupplierpaymentdocument_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="new_museum",
            field=models.ManyToManyField(
                blank=True,
                related_name="new_operation_items",
                to="TourManager.museum",
                verbose_name="Müzeler (博物馆)",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_operation_items",
                to="TourManager.museum",
                verbose_name="Müze (博物馆)",
            ),
        ),
    ]
