# Generated by Django 4.2.9 on 2024-04-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0060_operationitem_new_museum_alter_operationitem_museum"),
    ]

    operations = [
        migrations.AddField(
            model_name="personel",
            name="job",
            field=models.CharField(
                choices=[
                    ("Satis_Personeli", "Satış Personeli"),
                    ("Operasyon_sefi", "Operasyon Şefi"),
                    ("Sistem_Gelistiricisi", "Sistem Geliştiricisi"),
                    ("Yonetim", "Yönetim"),
                ],
                default="Satis_Personeli",
                max_length=20,
                verbose_name="Görevi",
            ),
        ),
    ]
