# Generated by Django 4.2.9 on 2024-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourManager", "0061_personel_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personel",
            name="job",
            field=models.CharField(
                choices=[
                    ("Satış Personeli", "Satış Personeli"),
                    ("Operasyon Şefi", "Operasyon Şefi"),
                    ("Sistem Geliştiricisi", "Sistem Geliştiricisi"),
                    ("Yönetim", "Yönetim"),
                ],
                default="Satış Personeli",
                max_length=20,
                verbose_name="Görevi",
            ),
        ),
    ]
