# Generated by Django 4.2.9 on 2024-04-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("TourManager", "0062_alter_personel_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
