from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Sirket)
admin.site.register(Personel)
admin.site.register(Tour)
admin.site.register(Transfer)
admin.site.register(Vehicle)
admin.site.register(Guide)
admin.site.register(Hotel)
admin.site.register(Activity)
admin.site.register(ActivitySupplier)
admin.site.register(Cost)
admin.site.register(Museum)
admin.site.register(Operation)
admin.site.register(OperationDay)
admin.site.register(OperationItem)
admin.site.register(FiyatlandirmaItem)
admin.site.register(Fiyatlandırma)
admin.site.register(UserActivityLog)
admin.site.register(PaymentDocument)
admin.site.register(SupplierPaymentDocument)
admin.site.register(ActivitySupplierPaymentDocument)